Sage-Bionetworks/synapseAnnotations

synapseAnnotations/data/common/minimal_Sage_standard.json

This is to clear up the issue of having primary cells in cellTypes. There are four cells I added in my last pull request that are primary or the not primary equivalent (arachnoid, primary arachnoid, meningioma, primary meningioma). 
@teslajoy removed the primary arachnoid and primary meningioma for me, and I'm adding an isPrimary boolean to make it easy to flag these cell lines (allowing me to just annotate these lines as arachnoid or meningioma, with isPrimary True or False).
I also added a couple other changes that I mentioned in issues in the past week.

added isPrimary key and few other values to minified

---

synapseAnnotations/data/neurofibromatosis.json

"genotype" doesn't capture all of the genetic perturbations in the NF1/NF2 datasets. for example, HS01 cells have constitutively expressed shRNA targeting NF2 that results in extreme NF2 deficiency, but it is still NF2 +/+ 
renaming the key expands it's utility. could explore changing "-/-" to "deficient"in the scenario illustrated above.

renamed key "nf1/nf2genotype"

---

README.md

to annotationReleaseVersion to avoid overlap with synapse annotations and unify naming convention with annotations table

changed annotationVersion

---

synapseAnnotations/data/compoundScreen.json

Adding compoundDoseRange, a string that represents the min-max values of a drug/compound/antibody treatment range.

add compoundDoseRange

---

synapseAnnotations/data/cancer.json

To resolve #357. Errant key that is not really defined. Overlaps with terms in neuro that are currently in use.

remove modelSystem

---

synapseAnnotations/data/experimentalData.json

A collaborator has samples where they didn't separate two brain tissues and would like to indicate them both in the annotations:
"We didn’t separate VZ and SVZ in the brain dissection so would prefer using VZ/SVZ as the term. The description will be 'VZ/SVZ are proliferative transient zones situated near the surface of the cerebral lateral ventricles'."
The definitions separately for the two regions are:
**ventricular zone**: Proliferative region that is part of the ventricular system
**subventricular zone**: The subventricular zone (SVZ) is a paired brain structure situated throughout the lateral walls of the lateral ventricles. Along with the subgranular zone of dentate gyrus, subventricular zone serves as a source of neural stem cells in the process of adult neurogenesis. It harbors …

Added value VZ/SVZ to tissue key

---

synapseAnnotations/json_schema/ontology/analysis.json
synapseAnnotations/json_schema/ontology/array.json
synapseAnnotations/json_schema/ontology/cancer.json
synapseAnnotations/json_schema/ontology/chem.json
synapseAnnotations/json_schema/ontology/compoundScreen.json
synapseAnnotations/json_schema/ontology/curatedData.json
synapseAnnotations/json_schema/ontology/dhart.json
synapseAnnotations/json_schema/ontology/experimentalData.json
synapseAnnotations/json_schema/ontology/genie.json
synapseAnnotations/json_schema/ontology/network.json
synapseAnnotations/json_schema/ontology/neuro.json
synapseAnnotations/json_schema/ontology/neurofibromatosis.json
synapseAnnotations/json_schema/ontology/ngs.json
synapseAnnotations/json_schema/ontology/sageCommunity.json
synapseAnnotations/json_schema/ontology/tool.json
synapseAnnotations/json_schema/ontology/toolExtended.json

As part of #351/#375 this creates an `ontology/` folder within `json_schema/`. As a first pass I've just copied every annotation that has multiple options in `enumValues` to the folder.

Add existing annotations to ontologies folder

---

synapseAnnotations/data/sageCommunity.json

I have lots of "report" files to annotate. This used to be an annotation but is gone now (was under dataType, or dataSubtype?). Would be a helpful annotation for the purposes of filtering out human readable data (powerpoints, docs, pdfs). My only concern is having a clear definition that separates this from "analysis" - hopefully this is enough for that distinction: "A report is not a single figure."

add resourcetype = report

---

synapseAnnotations/data/experimentalData.json

This repo is like an astronaut - weightless. 
We have `assay = scale` but no equivalent `dataType`.

add datatype weight

---

synapseAnnotations/data/experimentalData.json

This adds `"clinical"` as a data type. Though we haven't fully resolved the dataType question in #421, in conversation with @ychae we realized that `"clinical"` is already being used frequently as a dataType and should be reflected in our annotations. This is also consistent with GDC's data types, and I've made sure to use the same definition [they use](https://github.com/NCI-GDC/gdcdictionary/blob/edd332190a8503b84f02fc532e72dcd8fda04370/gdcdictionary/schemas/clinical.yaml#L11-L12) in case we do more fully adopt their model.

Add clinical as a dataType

---

synapseAnnotations/data/experimentalData.json

As discussed in the meeting today. I did not find an existing ontology term, and left the description fairly broad. I didn't want to restrict it to _actually_ the entire brain, because we have samples that are from one hemisphere, and I think "whole brain" is still functionally the correct value even though it's technically not the whole brain.

Add "whole brain" as a tissue

---

synapseAnnotations/data/experimentalData.json

I've used "immunoassay" (an exact synonym) rather than "Immunology Test" (the preferred term) because it appears that "immunoassay" is already in use in AMP-AD. However if we'd prefer to switch to the preferred term I'm happy to update.

Add ELISA as assay and immunoassay as dataType

---

synapseAnnotations/data/experimentalData.json

This value was already used in the SUNYStrokeModel study in AMP-AD but was never added to the annotations dictionary.

Add electrophysiology as dataType

---

.travis.yml

jsonlint can't lint multiple files at once, so this has only been linting the first json file in the repo, not all of them.

Lint all json files in the repo

---

synapseAnnotations/data/experimentalData.json

There are some duplicate values within the tissue annotation. I have removed the duplicates; all the terms are still present.
* [medial orbital frontal cortex](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/f796edd7fcf4bfd9293155123c2d65d826df016c/synapseAnnotations/data/experimentalData.json#L876)
* [medial prefrontal cortex](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/f796edd7fcf4bfd9293155123c2d65d826df016c/synapseAnnotations/data/experimentalData.json#L881)
* [inferior temporal cortex](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/f796edd7fcf4bfd9293155123c2d65d826df016c/synapseAnnotations/data/experimentalData.json#L891)
* [medial dorsal nucleus of thalamus](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/f796edd7fcf4bfd9293155123 …

Remove duplicate tissue annotations

---

tests/integration/test_json.py

* Fixes test so that it correctly understands the a) structure and b) location of our json data
* Updates to work with python 3.6 (which is the default on travis)
Note that it will only show an error for the first duplicate it finds. I think this was how the original test was written too, but we can update it if we want to show all duplicates at once.
This should probably fail travis checks since there are currently duplicate values until #480 and #483 are merged. See also #482.
Review on the pythonic-ness of the code is welcome, it's been a while since I wrote any python...

Fix test for duplicate values

---

synapseAnnotations/data/experimentalData.json

Closes #470. Adds `metadataType` key with possible values: individual, biospecimen, assay, data dictionary, and protocol.

Add metadataType annotation

---

synapseAnnotations/data/experimentalData.json

If `dataType = proteomics` then it makes sense for an acceptable `assay` value to be a subtype of proteomics. In this case - TMT.

add type of proeomics assay

---

synapseAnnotations/data/experimentalData.json

The "individualID" key in the experimentalData module did not have a definition, so I gave it one based on the definition of "specimenID" that Kelsey suggested.

Add individualID description

---

synapseAnnotations/data/experimentalData.json

Add "Head of caudate nucleus" to tissue key. This was proposed by a collaborator; we already have "caudate nucleus" but their tissue is more specific. "Head of caudate nucleus" should be used if the tissue sample was specific to that part of the caudate nucleus; "caudate nucleus" should be used otherwise.

Add head of caudate nucleus

---

synapseAnnotations/data/experimentalData.json

The word "description" was misspelled as "desription" in the "open field test" value under the "assay" key.

Fixed typo in assay key

---

synapseAnnotations/data/experimentalData.json

Leaving the capitalization as-is, even though the new source writes it "Orbitrap"

Update source for orbitrap fusion

---

synapseAnnotations/data/experimentalData.json

This is a higher priority as it is preventing a PsychENCODE contributor from uploading data.

Added UCSF to individualIdSource

---

synapseAnnotations/data/sageCommunity.json

Update of source for AMP-AD/M2OVE-AD/MODEL-AD/Resillience-AD to point to the portal instead of Synapse

Source update

---

synapseAnnotations/data/experimentalData.json

I added two terms by request from PEC researchers. The term "insular cortex" does not have a definition but its parent does. Can we still accept this case?

add two tissue terms

---

.gitignore
README.md
update_annotations_table.R

The code in annotator that updates the table of synapse annotations has been broken for a while and doesn't seem like it's going to be actively maintained. I wrote a script to update the table, thinking it might be useful to keep that within this repo where we can continue to maintain it. 
The table looks ok to me, but something seems to be broken now in the annotationUI shiny app. I've opened a Jira ticket to request access to view the logs; if there's something in this script that is causing the issue I'll fix it.

Add script to update table

---

synapseAnnotations/data/immunoAssays.json

I used the generic "catalogNumber" and "lotNumber" keys instead of "antibodyCatalogNumber", and "antibodyLotNumber" so that I could a) include a source, and b) allow for greater reuse of the term.  I have not seen multiple uses of catalog and lot numbers in the metadata in my previous experience with immunoassays, but let me know if this is not the case and I'll get more specific with the names.  I also used "vendor" instead of "antibodyVendor" to allow for reuse of the term.  I did find a source for "vendors", but it seemed very broad (A person or agency that promotes or exchanges goods or services for money) so I elected not to include it.  If we stick with the generic keys, it's possible that they may have uses outside of immunoassays and should be in another module, and I'll move the …

Terms for immunoassays

---

synapseAnnotations/data/immunoAssays.json

I looked at EpiMap CHIPSeq data and the chromatinAmount column is a decimal.  I had it typed as an integer.  I saw by looking at other annotations modules that decimal numbers are type as STRING, so I changed the typing from INTEGER to STRING.

Retype chromatin amount

---

synapseAnnotations/data/analysis.json

One use case is for differential expression for chromatin activity, which was being excluded by the original definition. The source did not change because the language for this newer definition is in the source.

Update definition of differential expression to be more inclusive

---

synapseAnnotations/data/experimentalData.json

This is debatable on whether we really need this or if there is a better way to indicate the types of ELISA assay (assuming that is needed). We have "sandwich ELISA" and "ELISA" as different assays. However, it would be nice to be able to have all ELISA assays under the ELISA annotation. Then further refinement of the data set by elisaType could be done.

Add elisaType to specify a specific type of ELISA assay

---

.gitignore

example_schema_usage.py downloads credentials to the directory where it's run, which would make it easy to accidentally commit it to the repo. Adding credentials.json to the .gitignore should make that less likely to happen by accident.

gitignore credentials.json

---

README.md
synapseAnnotations/README.md

Adds documentation of the important files within the `synapseAnnotations/` subfolder. @milen-sage, there are many other scripts that I don't know the purpose of, I know you're planning to refactor some of this in the next week so I didn't go too far in trying to figure them out. One thing I did find confusing is that there's a `schemas/` subfolder, but both `sage_controlled_vocabulary_schema.csv` and `sage_schema.jsonld` are in the the `synapseAnnotations/` folder rather than in this subfolder. Should they be moved?

Add documentation of the important scripts 

---

terms/experimentalData/individualIdSource.json

Added the Vaccarino Lab to individualIdSource. Schema was compiled using ajv compile -s and is valid.

IndividualIdSource-Vaccarino

---

terms/experimentalData/diagnosis.json

Add no cognitive impairment and control to diagnosis. This one is a bit tricky since 'control' isn't technically a diagnosis. However, we have data contributors who are using this to designate control versus non-control patients.
@cw-dvr8, no cognitive impairment is in the AD annotations table so that's one you don't need to add yourself.

Add control and no cognitive impairment diagnosis

---

terms/experimentalData/assay.json

pharmacodynamic and pharmacology are assays for dataType 'pharmacokinetic study'. The rest of the assay terms being added are for dataType 'metabolomics'. These seem like platforms/libraryPreparationMethods, but the contributors were adamant that these should be the assay names.

Add metabolomics and pharmacokinetic assays

---

.github/workflows/check-schemas.yaml

This adds a GitHub Actions workflow to check that the mini-schemas in `terms/` are 1) valid JSON Schema (using ajv-cli), and 2) contain only ASCII characters, as non-ASCII characters can cause some issues when registering schemas.
There are some other checks I'd like to add going forward, but they're a little more complicated, so I thought I'd start with this since it's useful and not too complicated.

Set up GitHub Actions to validate schemas

---

terms/experimentalData/failedQC.json

This brings it in line with other boolean annotations, e.g. `isCellLine`

Make failedQC a proper boolean

---

.Rprofile
.github/workflows/register-schemas-dryrun.yaml
README.md
register-schemas.R
renv.lock
renv/.gitignore
renv/activate.R
renv/settings.dcf

This adds a GitHub Actions workflow that will test all added or changed schemas in a pull request against Synapse's schema registration endpoint with `dryRun: true`. This will ensure that schemas that are changed in a PR will be able to be successfully registered on Synapse. It does _not_ actually register them (that should probably happen in a separate action after merging the PR).
To achieve this, I've reworked the `register-schemas.R` script so it can more easily be called from the command line with a few different options. I've also set up the repo to use renv for managing dependencies, so that GitHub actions can install the correct packages. `activate.R` is auto-generated by renv and shouldn't be reviewed.
For this workflow to run, it needs Synapse credentials. I've created a service …

Add workflow to check that schemas can be registered

---

terms/experimentalData/SentrixID.json
terms/experimentalData/SentrixRowColumn.json

Add SentrixID and SentrixRowColumn as new keys. These are terms from Illumina's BeadChip technology for their array-based assays. The SentrixID is the chip ID and the SentrixRowColumn is the position of the sample in the chip.
I put this in experimentalData. Should these be in a different module?

Add SentrixID and SentrixRowColumn

---

terms/experimentalData/tissue.json

Splitting hairs on whether some of these are actually "tissues," but we are using these in AD to differentiate between sample types for microbiome studies.

Add tissues for microbiome studies

---

terms/immunoAssays/elisaType.json
terms/immunoAssays/fluorophore.json

fluorophore seems straightforward.
elisaType relates to the ELISA assay. Technically, we have assay terms like "sandwich ELISA" that would cover this term. However, the idea for this was to be able to have an "ELISA" assay (simpler for queries) and just specify the type. Not sure if we want to keep this, though. @amapeters, thoughts on this?

Add fluorphore and elisaType

---

terms/immunoAssays/fluorophore.json

Max length of descriptions for keys/values is 250 in the table generated from the terms. Simplified description to get under that limit.

Shorten definition of fluorophore

---

terms/experimentalData/reprogrammedCellType.json

I thought I had removed all the odd spacing characters, but missed one. Spacing _should_ be fine now.

Fix odd spacing character

---

terms/experimentalData/reprogrammedCellType.json

This has been a 'fun' term. Originally, the idea was to not version this term so that it would stay in sync with whatever cellType had, without having to change this term, as well. However, this reduces the ability to use versioning to control what values are available to a downstream consortia schema. While it is more finicky to have to update reprogrammedCellType any time cellType is updated, the added benefit outweighs the annoyance.
This PR adds:
- a version to reprogrammedCellType $id. Note that I put this at 0.0.1 since it had no version previously.
- the most recent version to the referenced cellType $id.

Add version to reprogrammedCellType and its reference

---

update-annotations-table.R

There are cases in which we want a term with a specific definition, but that has the same enumerated list of values as a different term. The example case is [reprogrammedCellType](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/master/terms/experimentalData/reprogrammedCellType.json), which should be in sync with cellType.
This script update allows for doing this. When the table is generated, every value in cellType has two rows: one with the key cellType and the cellType definition, one with the key reprogrammedCellType and the reprogrammedCellType definition.
Assumptions/restrictions:
- Does not allow for extending terms. This will only allow for referencing the values in **one** other schema, with no additional values.
- Reference is done via `property`, where the schema …

Table script update: allow referencing values of a different term

---

terms/neuro/study.json

Study values are for MODEL-AD and don't have longer names. "The X study (X)" is pretty redundant for description but this appears to be how we did it previously for UCI studies.

add new UCI study values

---

terms/experimentalData/chromosome.json

This creates a term for annotating with chromosome number. Format is an enumerated string, with values "1", "2", ... "22" + "X" and "Y". This can be updated if/when we get data from other species with different chromosome numbers and different sex chromosomes. 
I used "Sage Bionetworks" for the source for all values since chromosome number is pretty self-explanatory, but can change this if needed. 
Also open to making the values "chr1", "chr2", etc if that's more in line with what is typically used.

Create chromosome key

---

terms/experimentalData/chromosome.json

Removed the '.json' from the ID. Cannot update the table with this in the ID.
Also incremented the version, which is technically unnecessary, but doing so because it's good practice.

Fix chromosome ID

---

terms/neuro/study.json

There was some confusion with our UCI contributor, but the new UCI MODEL-AD data will be consolidated under one study called UCI_PrimaryScreen. I have renamed this one and removed the values for the individual model name studies.

remove UCI study names

---

terms/demographics/ageDeathUnits.json
terms/experimentalData/ageAssessment.json
terms/experimentalData/ageAssessmentUnits.json
terms/experimentalData/samplingAgeUnits.json

This PR adds values to the ageDeathUnits term and creates new terms for ageAssessment, ageAssessmentUnits, and samplingAgeUnits. All three "age units" terms have identical values; we don't anticipate needing to add values frequently, but when we do we should try to add to all age unit terms at once. We decided this would be simpler than aliasing the new terms to ageDeathUnits, but can revisit in the future if desired.

Update age and age unit terms

---

terms/experimentalData/chromosome.json
terms/experimentalData/specimenIdSource.json

- added a definition for the specimenIdSource key, which was previously missing, to clarify what we are looking for in in vivo and in vitro studies
- added "mitochondrial" as a chromosome value

add specimenIdSource definition and new chromosome value

---

terms/experimentalData/individualIdSource.json

this is for specimens from living donors, not the brain bank

add value for Mayo Clinic

---

terms/neuro/study.json

This must have been added at one point because it's an older study but it disappeared. Re-adding.

add AD-BXD study

---

terms/ngs/commercialSource.json
terms/ngs/libraryType.json
terms/ngs/nucleicAcidSource.json

The PR: 
- Adds a new key commercialSource for nucleic or amino acids purchased from a private company. The goal here is to surface an accession number. 
- Modifies the definition of `libraryType` to be slightly more permissive. For this use case, this key is to also be applicable to plasmid insert ampliciation which is pooled but not _necessarily_ multiplexed.  
- Adds value `plasmid DNA` to `libraryType`
- Adds value `cell-free DNA` to `nucleicAcidSource`

New terms for STARRSeq assay

---

terms/experimentalData/reprogrammedCellType.json

Absolute paths were added in #851. The absolute paths for ids is fine, but these should not be used for referenced terms.
- Change back to relative path for cellType in reprogrammedCellType

Do not use absolute path for cellType reference in reprogrammedCellType

---

terms/experimentalData/reprogrammedCellType.json

The reprogrammedCellType schema was using a reference to cellType to keep both up to date with each other. This ended up being a bit of a pain due to failing CI checks when cellType is updated. Now that we have a web interface for editing annotations based on a schema, this term also looks odd in that interface.
Instead of sticking with the reference, this PR duplicates the cellType values in reprogrammedCellType. If one gets out of date with the other and is in need of updating, it is not difficult to create a PR to make the change.

Use enumerated cellType list instead of reference for reprogrammedCellType

---

.github/workflows/register-schemas-dryrun.yaml
.github/workflows/register-schemas.yaml
update-schema-version-table.R

A GH Action exists to test that newly added/modified files can be registered in Synapse, but the terms are not actually registered. This is a second action that would register the terms in Synapse once they are merged into the main branch. The code here is an updated version of the dryrun action.
GH Actions are tough to test before deploying, especially when they trigger on the main branch. If someone could skim this and gives a thumbs up if it looks okay, that would be great!
Edit: I also decided to throw in the table update since that should be done on merge to main, as well.

Add GH Action to register newly added or modified files on merge and update Synapse table

---

renv.lock
update-annotations-table.R
update-schema-version-table.R

Forgot that I had switched to reticulate + python client for the cron and didn't update the scripts to use synapser, again. Updated scripts and renv.lock to have latest synapser version.

Update synapser in renv.lock & use in table scripts

---

.github/workflows/register-schemas-dryrun.yaml
update-schema-version-table.R

Updates the schema version table to have an alias for each term in the format "module_key". This can then be used as an anchor in yaml files. Also adds the Synapse PAT to the dryrun GH Action that happens on PR.

Add alias to schema version table and Synapse PAT to GH Action

---

terms/analysis/analysisType.json

For now, all our various xQTL analysis types should follow the same format. I'm not convinced we should stick with the long form, but they should at least all match.
I also added the abbreviations for each to the definition, so that searching with the abbreviated term in the dictionary finds a match.

parallelize QTL values
