minimal_Sage_standard.yml
nf_annnotations.yml

We reviewed these in our meeting today.

Updated minified and added project-specific annotation file

---

minimal_Sage_standard.yml

Added more values to minified, keys remain the same.

Ntap motivated update

---

minimal_Sage_analysis.yml

Opening a PR for @blogsdon's issue #4 so we can comment/review specific regions.

Analysis annotations

---

minimal_Sage_analysis.yml

Added diffex and variant calling methods

---

minimal_Sage_standard.json
minimal_Sage_standard.yml
ntap_annotations/ntap_ncats_annotation_scheme.yml

Added new minified and ncats updated

---

minimal_Sage_standard.json
minimal_Sage_standard.yml

Changed some of the tumorTypes to reflect 2016 WHO reclassification of CNS tumors. Also clarified and added NF1/NF2 CNS/PNS tumor types

tumorType adjustments

---

minimal_Sage_standard.json

Specifically - chromatin activity should define atac, dnase and any looping stuff.

Added values for MSKCC CSBC Project

---

minimal_Sage_analysis.yml

specifically peak-calling and methods for that.

added chromatin activity specific methods

---

dhart_annotations.json
nf_annotations.json
onc_annotations.json

Let's discuss shiny new terms!!!

New onc annotations for CSBC

---

scripts/json2schema.py
synapseAnnotations/data/common/minimal_Sage_standard.json

Ignore hacky code - lots of stuff to make the order of the JSON keys prettier.

Minimal schema in Synapse schema format plus 

---

synapseAnnotations/data/common/minimal_Sage_analysis.json

I ran the conversion myself so we can add the descriptions on Tuesday per Issue #88

Converted analysis annotations to json so we can move forward

---

synapseAnnotations/data/common/minimal_Sage_standard.json

Adds description for these two one-off keys

Description for individualIdSource and isCellLine

---

synapseAnnotations/data/neuro_annotations.json

Add 'WallOfTargets' as a study

---

synapseAnnotations/data/common/minimal_Sage_standard.json
synapseAnnotations/data/nf_annotations.json

Updated NF term descriptions and moved around some values to minified.

NF terms and more

---

synapseAnnotations/data/common/minimal_Sage_standard.json
synapseAnnotations/data/nf_annotations.json

I added a couple of assay types and cell types that are used frequently in the Synodos NF2 data. I also added an "unknown" to NF1/NF2 genotype in NF_annotations as the data do not always exist to confirm genotype status

additional cell types and assay types for NF2 datasets

---

synapseAnnotations/data/ngs_annotations.json

Check out issue #123 for details.

add read orientation, strand origin to ngs annotations

---

synapseAnnotations/data/common/minimal_Sage_standard.json
synapseAnnotations/data/onc_annotations.json

This is a pretty big commit - would be interested to think what @kdaily, @allaway think of it.  I'm trying to get to more details without being ridiculous.

Added additional oncology-related annotations

---

synapseAnnotations/data/common/minimal_Sage_standard.json

We need some terms to describe survey data.

added values for PRO data

---

docs/sample_schema.json

for documentation purposes @kdaily can you add additional possible values?

Created a sample schema

---

synapseAnnotations/data/tool_annotations.json
synapseAnnotations/data/tool_annotations_extended.json

All software has a language, will remove platform/script/binary distinction for now

removed language distinction

---

synapseAnnotations/data/neuro_annotations.json

Added keys: modelSystemNameCommon and modelsSystemStrainNomenclature
Added values: APP/PS1 and B6.Cg-Tg(APPswe,PSEN1dE9)85Dbo/Mmjax

Added two new keys to neuro with one value per key

---

synapseAnnotations/data/experimentalData.json

Added Illumina NextSeq500

---

README.md

add info on process for proposing changes, clean up and clarify some existing text

Update README.md with info on how to propose changes

---

synapseAnnotations/data/experimentalData.json

issue #213 resolution from meeting

pancreas to pancreatic cancer

---

synapseAnnotations/data/sageCommunity.json

Reverts Sage-Bionetworks/synapseAnnotations#197

Revert "added values narrowPeak, broadPeak, and gappedPeak to fileFormat key"

---

synapseAnnotations/data/analysis.json

added analysisType - genotypeImputation

---

CHANGELOG.md
README.md

Add in changelog.md

---

synapseAnnotations/data/experimentalData.json

change source URL directly to UBERON

change source URL directly to UBERON for 'middle frontal gyrus'

---

synapseAnnotations/data/sageCommunity.json

added r script to file format

---

synapseAnnotations/data/sageCommunity.json

added tar archive to fileFormat

---

synapseAnnotations/data/experimentalData.json

from http://purl.obolibrary.org/obo/NCIT_C13018
closes #119

fixed organ definition

---

synapseAnnotations/data/tool.json

added new software types

---

synapseAnnotations/data/analysis.json

Added new annotations to describe the ongoing NF-related analysis that will be used to build dashboards.

Updated analysis annotations

---

synapseAnnotations/data/experimentalData.json

Remove species information. issue #224

Update platform values' description

---

synapseAnnotations/data/tool.json

Update inputDataType and outputDataType

---

synapseAnnotations/data/tool.json

Add "pathway or network" to inputDataType and outputDataType

Add "pathway or network"

---

synapseAnnotations/data/analysis.json

fixed capitalization and synced preferred names

---

CONTRIBUTING.md

add drug terms best practices to contributing doc

---

synapseAnnotations/data/tool.json

use case: https://shiny.synapse.org/users/rallaway/polypharmacology-db/

add chemical input/outputs

---

synapseAnnotations/data/experimentalData.json
synapseAnnotations/data/network.json
synapseAnnotations/data/tool.json

larger update to create networkType and update network annotations

---

synapseAnnotations/data/sageCommunity.json

edited description of plink files

---

synapseAnnotations/data/ngs.json

Very rough start, works on issue #339

updated ngs.json to accommodate scRNA-Seq data

---

synapseAnnotations/data/compoundScreen.json

To cover newer NF2 data and some older screening data.

New and corrected compound names.

---

synapseAnnotations/data/experimentalData.json

Updated terms for JMML spore data

---

synapseAnnotations/data/experimentalData.json

Cover assays: 'novelty response behavior' (emotional) and 'active avoidance learning behavior' (cognitive)

Added dataType - behavior process

---

README.md

Fix relative links in README.md

---

synapseAnnotations/data/compoundScreen.json
synapseAnnotations/data/experimentalData.json
synapseAnnotations/data/neuro.json

A few updates to account for NF data

NF-related additions

---

synapseAnnotations/data/experimentalData.json

This is tangentially related to #405, but for now I only added embryonic stem cells to cellType.

Added embryonic stem cells to cellType

---

synapseAnnotations/data/cancer.json
synapseAnnotations/data/experimentalData.json

Perhaps we need a more generic term for methylation sequencing instead of scCGIseq (the latter is a new method that has not been added to more standard ontologies, yet)? For now I added it under assays, but we can always substitute it.

Additions to entries in species, assay, platform, organ in experimentalData.json; additions to tumorType in cancer.json 

---

CONTRIBUTING.md
README.md

Move Development section of README to CONTRIBUTING.md

---

synapseAnnotations/data/sageCommunity.json

zip, mov, hyperlink (for external links to google sheets, docs, etc manifested as a a synapse entity), svs, ab1, 7z, gff3, gson, sqlite, svg.

add file formats

---

CHANGELOG.md
synapseAnnotations/data/sageCommunity.json

we are merging these consortia annotations together.

consolidate Synodos

---

synapseAnnotations/data/experimentalData.json
synapseAnnotations/data/sageCommunity.json

* Add `"Resilience"` as a consortium (@amapeters should this be `"Resilience-AD"`?)
* Add `"JAX"` as an individualIdSource

Add some AMP-AD related annotation values

---

synapseAnnotations/data/experimentalData.json

Update organ in experimentalData.json

---

synapseAnnotations/data/experimentalData.json

("contextual conditioning behavior" has no description on the term page)

Add behavioral assays

---

README.md

@kdaily does this look good to you?

Document annotations release process

---

synapseAnnotations/data/experimentalData.json

creating drug combination data type

---

synapseAnnotations/data/experimentalData.json

We'll use this for rnaseq data from drosophila, where the samples consist of multiple pooled fly heads.

Add "bodyPart" key and "head" value

---

README.md

Add more info on how to perform release

---

synapseAnnotations/data/experimentalData.json

Like a drug screen/cell viability assay, but with a more complicated set of readouts. 
http://www.ebi.ac.uk/efo/EFO_0007550

add high content screen assay

---

synapseAnnotations/data/experimentalData.json

Related to #449 (though we could, if we want, add additional types of flags).

add failedQC annotation

---

synapseAnnotations/sage_annotations_2_biothings.py

I haven't been able to run @milen-sage's code and get the same output, so I can't verify this is correct, but I believe there's another instance of `first_upper()` that should be removed per #465. Opening this now so we can hopefully discuss in the meeting later today.

More case fixes

---

.gitignore

Any others we want to add now?

Add a .gitignore for files that should not be committed to the repo

---

synapseAnnotations/README.md
synapseAnnotations/sage_annotations_2_biothings.py

Closes #476. @milen-sage will you make sure I have captured this correctly?

Add readme for schema generation

---

synapseAnnotations/data/experimentalData.json

Added Buffy Coat (http://purl.obolibrary.org/obo/NCIT_C84507) to tissue and organ.

added buffy coat to tissue&organ

---

synapseAnnotations/data/neuro.json
synapseAnnotations/data/sageCommunity.json

I believe between this and #480 all of the duplicate values referenced in #482 should be fixed, however we still need to address the source of the problem and determine how these were introduced in the first place.

Remove some duplicate values in study and fileFormat

---

synapseAnnotations/data/array.json

It was not an array as expected.

fix array.json

---

synapseAnnotations/README.md
synapseAnnotations/convert_to_json_schema.R
synapseAnnotations/schemas/handcrafted-schemas/README.md
synapseAnnotations/schemas/handcrafted-schemas/ampad_demo.json
synapseAnnotations/schemas/handcrafted-schemas/ampad_schema.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/analysis.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/array.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/cancer.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/chem.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/compoundScreen.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/curatedData.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/dhart.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/experimentalData.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/genie.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/network.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/neuro.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/neurofibromatosis.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/ngs.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/sageCommunity.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/tool.json
synapseAnnotations/schemas/handcrafted-schemas/definitions/toolExtended.json
synapseAnnotations/schemas/handcrafted-schemas/nf_demo.json
synapseAnnotations/schemas/handcrafted-schemas/nf_schema.json

Adds everything from the json-schema-conversion branch so that we have all the work we've been doing in one place. After this is merged I think we should delete the other branch to reduce confusion.

Add json schema definitions and sample schemas

---

synapseAnnotations/data/neuro.json

Put modelSystemName values in alphabetical order so it's easier to see what's already been documented

Organize modelSystemName

---

synapseAnnotations/data/neuro.json

Added levetiracetam, updated description and source for haloperidol and placebo

Updated treatmentType

---

CONTRIBUTING.md

Text said "see below" for information that is not below, but rather in a different location.

Reword sentence in contributing guide

---

synapseAnnotations/data/neuro.json

Add studies for November 2019 data release; put MODEL-AD studies in alphabetical order

Add MODEL-AD studies

---

synapseAnnotations/data/experimentalData.json

elevated plus maze test, open field test, rotarod performance test, contextual fear conditioning test

added mouse behavior assays

---

synapseAnnotations/data/experimentalData.json

Add manifest as a metadataType

---

synapseAnnotations/data/experimentalData.json

"IlluminaNovaseq6000" and "OrbiTrap Fusion"

Added platforms

---

synapseAnnotations/data/experimentalData.json
synapseAnnotations/data/neuro.json
synapseAnnotations/data/ngs.json

Remove boolean enumerated values

---

synapseAnnotations/data/experimentalData.json

Added a description for the "sex" key in experimentalData.

Added a description for the sex key

---

synapseAnnotations/data/neuro.json

New studies

---

synapseAnnotations/data/experimentalData.json

Because sometimes we have HPLC without the MS!

assay: HPLC

---

synapseAnnotations/data/ngs.json

Add the value "PCRfree" to the values list for the libraryPrep key.

Add PCRfree to libraryPrep

---

synapseAnnotations/data/experimentalData.json

progressive supranuclear palsy and mild cognitive impairment

Add new diagnoses

---

synapseAnnotations/data/ngs.json

Add DNALibraryConstruction to libraryPrep

New library prep

---

synapseAnnotations/data/experimentalData.json

Add values to individualIdSource

New individual ID sources

---

synapseAnnotations/data/experimentalData.json

Add HiSeq1000 to the platform values list.

HiSeq1000 platform

---

synapseAnnotations/data/experimentalData.json

UM-BTB = University of Maryland Brain and Tissue Bank

Add UM-BTB to individualIdSource

---

synapseAnnotations/data/sageCommunity.json

Add fileFormats mex and cloupe for 10x cellranger files

---

synapseAnnotations/data/neuro.json

Add MCSA study

---

synapseAnnotations/ManifestGenerator.py

Added support for different colors for conditionally optional and required attributes; updated colors.

updated manifest generator 

---

synapseAnnotations/README.md

Part of #592. @milen-sage do you think this is sufficient or is more information needed here?

Add documentation of schema csv

---

synapseAnnotations/schemas/amp_schema.csv
synapseAnnotations/schemas/amp_schema.jsonld

Eventually this will be replaced by having a context column in the main CSV, but for now we adapt the CSV into a new one for AMP's schema.

Add preliminary AMP-AD schema

---

register-schemas.R

Need to recurse through subfolders to find schemas

Fix schema registration script

---

terms/ngs/libraryPrep.json

Added terms necessary for receiving pooled scrnaSeq data.  Technical questions should be referred to @kelshmo .  The schema was compiled using ajv compile -s and is valid.

Added cellHashing and MULTIseq

---

terms/experimentalData/diagnosisDetail.json

Diagnosis subgroup (DSM or ICD code).  Schema was compiled using ajv compile -s and is valid

Add diagnosisDetail

---

terms/immunoAssays/antibodyConcentration.json
terms/immunoAssays/antibodyConcentrationUnits.json
terms/immunoAssays/antibodyDilution.json
terms/immunoAssays/antibodyOrder.json

Add keys to the immunoAssay module for AMP.

Add immunoAssay keys

---

terms/analysis/analysisType.json

Add genome-wide pleiotropy to analysisType.

Add genome-wide pleiotropy to analysisType

---

terms/experimentalData/metaboliteType.json

Add metaboliteType key and values.
@amapeters, will you please double check these? I also changed the 'beta' character in some of the definitions to the word 'beta' since this is not a standard symbol and may mess something up.

Add metaboliteType and values

---

terms/experimentalData/platformLocation.json

Add platformLocation to experimentalData

Add platformLocation

---

terms/experimentalData/batchSize.json
terms/experimentalData/ionMode.json

Accidentally put two keys on this branch. I can split, if needed, but these are relatively simple additions.

Add ionMode and batchSize to experimentalData

---

terms/experimentalData/controlType.json

Add controlType as a key and its enumerated values.
@cw-dvr8, controlType is a term in the table you are going through. You would not need to add this one.

Add controlType key and values

---

terms/experimentalData/dataType.json

Add dataTypes metagenomics and epigenomics.

Add metagenomics and epigenomics

---

terms/ngs/libraryPrep.json

Add amplicon to libraryPrep

---

terms/experimentalData/assayTarget.json

Add IE V1-V3 as an assayTarget.

Add IE_V1-V3 assayTarget

---

terms/neuro/study.json

Add new AD studies, NAPS and RR_APOE4.

Add new AD studies, NAPS and RR_APOE4

---

terms/experimentalData/cellType.json

Add peripheral blood mononuclear cell and lymphoblastoid cell line to cellTypes.

Add pbmc and lymphoblastoid cell line to cellType

---

terms/experimentalData/exclude.json
terms/experimentalData/excludeReason.json

'exclude' and 'excludeReason' are two separate terms, but put them in same PR since they go together.

Add exclude and excludeReason

---

terms/curatedData/referenceSet.json

Add 1000 Genomes phase 3 to referenceSet.

Genomes1000p3

---

terms/neuro/waterpH.json

Add waterpH for the pH of water fed to animals. Added to neuro module because there are other model-related terms here. Let me know if this should be moved.

Add waterpH

---

terms/sageCommunity/group.json

In converting to JSON schema my script created an empty object where probably it should be an empty string.

Fix empty source for group

---

terms/neuro/study.json

Add AD study scRNA-seq_wild_AD_mic

Add AD study scRNA-seq_wild_AD_mic

---

terms/immunoAssays/antibodyOrder.json

Add sources to antibodyOrder values. Without sources, the table script breaks.

Add sources to antibodyOrder values

---

terms/neuro/study.json

I forgot to update the version number when I added the HBI_scRNAseq study name

updated $id version to 0.0.5

---

.github/workflows/check-schemas.yaml

This will just make it a bit nicer looking in the list of workflows

Give check-schemas.yaml workflow a name

---

terms/experimentalData/platform.json

Add IlluminaMiSeq platform

---

terms/experimentalData/otherMedicalDx.json

Schema was compiled using ajv compile -s and is valid.

Add otherMedicalDx

---

terms/experimentalData/bindingDensity.json

Add bindingDensity key to experimentalData module.

Add bindingDensity

---

terms/experimentalData/cellType.json

Add immune cell value to cellType key.

Add immune cell

---

terms/batch/nanostringBatch.json

Add nanostringBatch key to batch module.

Add nanostringBatch

---

terms/neuro/study.json

There was a mistake in the study name, and contributor requested to change it slightly, as well.

Update AD study scRNAseq_microglia_wild_ADmice name

---

terms/ngs/dnaExtractionMethod.json

Add key dnaExtractionMethod to ngs module.

Add dnaExtractionMethod

---

terms/experimentalData/diagnosis.json

Add a bunch of new diagnoses.
This is a draft because I am waiting on a couple.

Add values to diagnosis

---

terms/analysis/analysisType.json
terms/experimentalData/diagnosis.json

add Mendelian randomization analysis value

add value to analysisType

---

terms/experimentalData/assay.json

Add CITEseq to assay

---

terms/analysis/analysisType.json

-update out of date source link for eQTL
-add source for meQTL
-add value for pQTL

add new analysisType value and update sources

---

terms/neuro/treatmentDose.json

Description make sense? I have it as a string so people could include units, timeframe, etc.

Add treatmentDose

---

terms/experimentalData/diagnosis.json

Add gliosis diagnosis

---

terms/experimentalData/platform.json

Add values for Biograph mCT and Olink Target 96

Add platform values

---

terms/neuro/treatmentType.json

- add values for control, Abeta42 oligomer, and Abeta42 fibril

Add treatment type values

---

terms/neuro/treatmentDuration.json

This adds a term for treatmentDuration that is a free string (meant to accompany treatmentType and treatmentDose).

add new term for treatmentDuration

---

terms/experimentalData/platform.json
terms/experimentalData/spectrometerFrequency.json

- add platform value for Bruker Avance III
- add new key for spectrometer frequency
These are for the AD metabolomics assay metadata template.

Add nightingale NMR keys

---

terms/experimentalData/MRItype.json
terms/experimentalData/contrastAgent
terms/experimentalData/fieldStrength.json
terms/experimentalData/filename.json
terms/experimentalData/ligand.json
terms/experimentalData/scanID.json
terms/manifestKeys/filename.json

This PR adds terms for 6 new AD-related keys for MRI, PET, and autorad templates.

Add AD assay metadata template keys and values

---

terms/experimentalData/assayTarget.json

Added three values

---

terms/experimentalData/individualIdSource.json
terms/experimentalData/metaboliteType.json

Add new values for individualIdSource and metaboliteType.

New AD values

---

terms/experimentalData/assayTarget.json

This PR adds "R-loops" as an accepted value for assayTarget.

Add assay targets for DRIP-seq assay

---

terms/PsychENCODESpecific/study.json

NeuralRloops and iPSC-RNA-ATAC

Added 2 studies

---

terms/experimentalData/assayTarget.json

Since the list of assayTarget values is so long, proposing to alphabetize the values as it gets listed in this order in the metadata templates. 
Quick review, thanks @avanlinden !

alphabetize terms

---

terms/experimentalData/sourceCell.json

Same definition and source as cellType term.

add B-lymphocytes

---

update-annotations-table.R

The script for generating the dictionary table needed to be updated to account for absolute paths added in #853.
I also added an extra bit to generate a table with the key, latestVersion, and schema for tracking latest versions. I can imagine some places where I'd like to have an easier way to access that information.
Tested full script locally.

Update table script to account for absolute paths & add version table

---

.github/workflows/register-schemas.yaml

Specifically use Rscript in GH Action

---

terms/experimentalData/individualIdSource.json
terms/ngs/libraryPrep.json

Add new libraryPrep and individualIdSource values for the FreshMicro AD study.

Add ad values

---

terms/neuro/treatmentType.json

Add treatmentType

---

terms/experimentalData/assay.json
terms/experimentalData/platform.json

This PR include two changes:
1. add Illumina_Omni2.5-8 to platform
2. add m6a-rnaSeq to assay

Add platform and assay keys

---

terms/clinical/familyHistoryDetails.json

add term familyHistoryDetails in order to add it to PEC individual metadata template.

add familyHistoryDetails schema

---

terms/clinical/postmortemToxDetails.json

add term postmortemToxDetails in order to add it to PEC individual metadata template

add postmortemToxDetails schema

---

terms/neuro/individualCommonGenotype.json

Added Trem2-R47H_NSS and 5XFADTrem2-R47H_NSS

Add values to individualCommonGenotype.json

---

terms/sageCommunity/consortium.json

Add ELITE
Second attempt PR because of problems with dpulls

add ELITE consortium value

---

terms/analysis/analysisType.json
terms/experimentalData/assay.json
terms/experimentalData/dataSubtype.json
terms/experimentalData/individualIdSource.json
terms/neuro/isMultiome.json
terms/neuro/modelSystemName.json
terms/ngs/libraryPrep.json
terms/sageCommunity/fileFormat.json

Adding several values to existing terms and creating one new term for multiome data.

miscellaneous AD metadata updates
